In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('Walmart_sales.csv')
data.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [6]:
# setting the date column right
data['Date'] = pd.to_datetime(data['Date'], format='mixed')
data.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,2010-05-02,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,2010-12-02,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,2010-02-19,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,2010-02-26,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,2010-05-03,1554806.68,0,46.50,2.625,211.350143,8.106

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         6435 non-null   int64
 1   Date          6435 non-null   datetime64[ns]
 2   Weekly_Sales  6435 non-null   float64
 3   Holiday_Flag  6435 non-null   int64
 4   Temperature   6435 non-null   float64
 5   Fuel_Price    6435 non-null   float64
 6   CPI           6435 non-null   float64
 7   Unemployment  6435 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(2)
memory usage: 402.3 KB

In [10]:
data.nunique()

Store             45
Date             143
Weekly_Sales    6435
Holiday_Flag       2
Temperature     3528
Fuel_Price       892
CPI             2145
Unemployment     349
dtype: int64

In [11]:
data.shape

(6435, 8)

In [12]:
data.isna().sum()

Store           0
Date            0
Weekly_Sales    0
Holiday_Flag    0
Temperature     0
Fuel_Price      0
CPI             0
Unemployment    0
dtype: int64

In [13]:
# export the data to a new csv file
data.to_csv('Walmart_sales_cleaned.csv', index=False)

In [47]:
import pandas as pd

# Define the answers for Excel, SQL, and Power BI
excel_answers = [
    "Excel is used for data management, analysis, and visualization.",
    "A workbook contains multiple sheets; a worksheet is a single sheet.",
    "VLOOKUP finds and retrieves data based on a matching value.",
    "CONCATENATE combines text or cell values into one.",
    "Remove duplicates in Excel by selecting data and using 'Remove Duplicates.'",
    "PivotTable summarizes and analyzes data for insights.",
    "HLOOKUP searches horizontally; VLOOKUP searches vertically.",
    "Find & Replace data in Excel through the Home tab.",
    "COUNT counts numbers; COUNTA counts non-empty cells; COUNTIF counts based on criteria; COUNTIFS counts with multiple criteria.",
    "Conditional formatting visually highlights data based on conditions.",
    "Comparative operators compare values; IF statements make decisions based on conditions.",
    "Use the ROUND function to round values to 2 decimal places.",
    "Relative cell references adjust when copied; absolute references stay fixed.",
    "Line charts show trends over time; scatterplots display correlations between variables.",
    "TRIM removes extra spaces from text strings.",
    "Link data between worksheets using cell references or named ranges.",
    "Filtering displays specific rows; sorting arranges data by values."
]

sql_answers = [
    "SQL is Structured Query Language, used for managing data in relational databases.",
    "An SQL statement is a command like SELECT, INSERT, UPDATE, or DELETE used to perform tasks in a database.",
    "A database is a structured collection of data. DBMS is software to manage databases, with types like relational (RDBMS), hierarchical, network, and object-oriented. Examples of RDBMS include MySQL, PostgreSQL, Oracle.",
    "A join combines rows from different tables based on related columns. Types include INNER JOIN, LEFT JOIN, RIGHT JOIN, and FULL JOIN.",
    "Primary key uniquely identifies each record in a table. Unique key ensures uniqueness but allows null values. Foreign key establishes relationships between tables.",
    "A schema represents the logical structure of data in a database, including tables, relationships, and constraints.",
    "CASE() function performs conditional logic in SQL, returning a result based on specified conditions.",
    "SELECT retrieves data, FROM specifies the table, JOIN combines tables, ON specifies join condition, WHERE filters rows, GROUP BY groups rows, HAVING filters grouped data, ORDER BY sorts results, LIMIT limits rows returned.",
    "BOOLEAN data field can have values TRUE, FALSE, and sometimes NULL.",
    "To prevent duplicate records, use the DISTINCT keyword in your SELECT statement.",
    "Renaming a column changes its permanent name in the table, while giving an alias provides a temporary name in a specific query."
]

power_bi_answers = [
    "Power BI is a Microsoft business analytics tool for data visualization, analysis, and sharing insights.",
    "Power Query is for data transformation, while Power Pivot is for data modeling and relationships in Power BI.",
    "Power BI Desktop is a free application for creating Power BI reports and dashboards on desktop computers.",
    "Data modeling in Power BI involves structuring data, creating relationships, and optimizing for analysis.",
    "Power Query is a data connection and transformation technology used in Microsoft Excel and Power BI. It allows users to easily connect to various data sources, transform data using a visual interface, and load it into their analysis tools.",
    "DAX is a formula language in Power BI for custom calculations and analysis on data.",
    "Filters in Power BI narrow down data displayed in visuals based on specific criteria.",
    "GetData in Power BI retrieves data from external sources for import into Power BI models."
]

In [48]:
# creating a dataframe with a sequence of numbers from 1 to max for each tool
total = [i for i in range(1, len(excel_answers)+1)]  +  [i for i in range(1, len(sql_answers)+1)] + [i for i in range(1, len(power_bi_answers)+1)]
df = pd.DataFrame({
    'Tool': ['excel'] * len(excel_answers) + ['sql'] * len(sql_answers) + ['power_bi'] * len(power_bi_answers),
    'Question': total,
    'Answer': excel_answers + sql_answers + power_bi_answers
})

In [49]:
df.shape

(36, 3)

In [50]:
df

        Tool  Question                                             Answer
0      excel         1  Excel is used for data management, analysis, a...
1      excel         2  A workbook contains multiple sheets; a workshe...
2      excel         3  VLOOKUP finds and retrieves data based on a ma...
3      excel         4  CONCATENATE combines text or cell values into ...
4      excel         5  Remove duplicates in Excel by selecting data a...
5      excel         6  PivotTable summarizes and analyzes data for in...
6      excel         7  HLOOKUP searches horizontally; VLOOKUP searche...
7      excel         8  Find & Replace data in Excel through the Home ...
8      excel         9  COUNT counts numbers; COUNTA counts non-empty ...
9      excel        10  Conditional formatting visually highlights dat...
10     excel        11  Comparative operators compare values; IF state...
11     excel        12  Use the ROUND function to round values to 2 de...
12     excel        13  Relative cell references adjust when copied; a...
13     excel        14  Line charts show trends over time; scatterplot...
14     excel        15       TRIM removes extra spaces from text strings.
15     excel        16  Link data between worksheets using cell refere...
16     excel        17  Filtering displays specific rows; sorting arra...
17       sql         1  SQL is Structured Query Language, used for man...
18       sql         2  An SQL statement is a command like SELECT, INS...
19       sql         3  A database is a structured collection of data....
20       sql         4  A join combines rows from different tables bas...
21       sql         5  Primary key uniquely identifies each record in...
22       sql         6  A schema represents the logical structure of d...
23       sql         7  CASE() function performs conditional logic in ...
24       sql         8  SELECT retrieves data, FROM specifies the tabl...
25       sql         9  BOOLEAN data field can have values TRUE, FALSE...
26       sql        10  To prevent duplicate records, use the DISTINCT...
27       sql        11  Renaming a column changes its permanent name i...
28  power_bi         1  Power BI is a Microsoft business analytics too...
29  power_bi         2  Power Query is for data transformation, while ...
30  power_bi         3  Power BI Desktop is a free application for cre...
31  power_bi         4  Data modeling in Power BI involves structuring...
32  power_bi         5  Power Query is a data connection and transform...
33  power_bi         6  DAX is a formula language in Power BI for cust...
34  power_bi         7  Filters in Power BI narrow down data displayed...
35  power_bi         8  GetData in Power BI retrieves data from extern...

In [51]:
# creating a new column with adding tool and   question 
df['Tool_Question'] = df['Tool']+ '_answer'+ '_' + df['Question'].astype(str)

In [52]:
df

,Tool,Question,Answer,Tool_Question
0,excel,1,"Excel is used for data management, analysis, a...",excel_answer_1
1,excel,2,A workbook contains multiple sheets; a workshe...,excel_answer_2
2,excel,3,VLOOKUP finds and retrieves data based on a ma...,excel_answer_3
3,excel,4,CONCATENATE combines text or cell values into ...,excel_answer_4
4,excel,5,Remove duplicates in Excel by selecting data a...,excel_answer_5
5,excel,6,PivotTable summarizes and analyzes data for in...,excel_answer_6
6,excel,7,HLOOKUP searches horizontally; VLOOKUP searche...,excel_answer_7
7,excel,8,Find & Replace data in Excel through the Home ...,excel_answer_8
8,excel,9,COUNT counts numbers; COUNTA counts non-empty ...,excel_answer_9
9,excel,10,Conditional formatting visually highlights dat...,excel_answer_10
10,excel,11,Comparative operators compare values; IF state...,excel_answer_11
11,excel,12,Use the ROUND function to round values to 2 de...,excel_answer_12
12,excel,13,Relative cell references adjust when copied; a...,excel_answer_13
13,excel,14,Line charts show trends over time; scatterplot...,excel_answer_14
14,excel,15,TRIM removes extra spaces from text strings.,excel_answer_15
15,excel,16,Link data between worksheets using cell refere...,excel_answer_16
16,excel,17,Filtering displays specific rows; sorting arra...,excel_answer_17
17,sql,1,"SQL is Structured Query Language, used for man...",sql_answer_1
18,sql,2,"An SQL statement is a command like SELECT, INS...",sql_answer_2
19,sql,3,A database is a structured collection of data....,sql_answer_3
20,sql,4,A join combines rows from different tables bas...,sql_answer_4
21,sql,5,Primary key uniquely identifies each record in...,sql_answer_5
22,sql,6,A schema represents the logical structure of d...,sql_answer_6
23,sql,7,CASE() function performs conditional logic in ...,sql_answer_7
24,sql,8,"SELECT retrieves data, FROM specifies the tabl...",sql_answer_8
25,sql,9,"BOOLEAN data field can have values TRUE, FALSE...",sql_answer_9
26,sql,10,"To prevent duplicate records, use the DISTINCT...",sql_answer_10
27,sql,11,Renaming a column changes its permanent name i...,sql_answer_11
28,power_bi,1,Power BI is a Microsoft business analytics too...,power_bi_answer_1
29,power_bi,2,"Power Query is for data transformation, while ...",power_bi_answer_2
30,power_bi,3,Power BI Desktop is a free application for cre...,power_bi_answer_3
31,power_bi,4,Data modeling in Power BI involves structuring...,power_bi_answer_4
32,power_bi,5,Power Query is a data connection and transform...,power_bi_answer_5
33,power_bi,6,DAX is a formula language in Power BI for cust...,power_bi_answer_6
34,power_bi,7,Filters in Power BI narrow down data displayed...,power_bi_answer_7
35,power_bi,8,GetData in Power BI retrieves data from extern...,power_bi_answer_8

In [53]:
df_1 = df.drop(['Tool', 'Question'], axis=1)

In [54]:
df_1

                                               Answer      Tool_Question
0   Excel is used for data management, analysis, a...     excel_answer_1
1   A workbook contains multiple sheets; a workshe...     excel_answer_2
2   VLOOKUP finds and retrieves data based on a ma...     excel_answer_3
3   CONCATENATE combines text or cell values into ...     excel_answer_4
4   Remove duplicates in Excel by selecting data a...     excel_answer_5
5   PivotTable summarizes and analyzes data for in...     excel_answer_6
6   HLOOKUP searches horizontally; VLOOKUP searche...     excel_answer_7
7   Find & Replace data in Excel through the Home ...     excel_answer_8
8   COUNT counts numbers; COUNTA counts non-empty ...     excel_answer_9
9   Conditional formatting visually highlights dat...    excel_answer_10
10  Comparative operators compare values; IF state...    excel_answer_11
11  Use the ROUND function to round values to 2 de...    excel_answer_12
12  Relative cell references adjust when copied; a...    excel_answer_13
13  Line charts show trends over time; scatterplot...    excel_answer_14
14       TRIM removes extra spaces from text strings.    excel_answer_15
15  Link data between worksheets using cell refere...    excel_answer_16
16  Filtering displays specific rows; sorting arra...    excel_answer_17
17  SQL is Structured Query Language, used for man...       sql_answer_1
18  An SQL statement is a command like SELECT, INS...       sql_answer_2
19  A database is a structured collection of data....       sql_answer_3
20  A join combines rows from different tables bas...       sql_answer_4
21  Primary key uniquely identifies each record in...       sql_answer_5
22  A schema represents the logical structure of d...       sql_answer_6
23  CASE() function performs conditional logic in ...       sql_answer_7
24  SELECT retrieves data, FROM specifies the tabl...       sql_answer_8
25  BOOLEAN data field can have values TRUE, FALSE...       sql_answer_9
26  To prevent duplicate records, use the DISTINCT...      sql_answer_10
27  Renaming a column changes its permanent name i...      sql_answer_11
28  Power BI is a Microsoft business analytics too...  power_bi_answer_1
29  Power Query is for data transformation, while ...  power_bi_answer_2
30  Power BI Desktop is a free application for cre...  power_bi_answer_3
31  Data modeling in Power BI involves structuring...  power_bi_answer_4
32  Power Query is a data connection and transform...  power_bi_answer_5
33  DAX is a formula language in Power BI for cust...  power_bi_answer_6
34  Filters in Power BI narrow down data displayed...  power_bi_answer_7
35  GetData in Power BI retrieves data from extern...  power_bi_answer_8

In [55]:
# creating a new dataframe with tool_question as columns and answers as values
df_2 = df_1.T

In [56]:
df_2

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
Answer,"Excel is used for data management, analysis, a...",A workbook contains multiple sheets; a workshe...,VLOOKUP finds and retrieves data based on a ma...,CONCATENATE combines text or cell values into ...,Remove duplicates in Excel by selecting data a...,PivotTable summarizes and analyzes data for in...,HLOOKUP searches horizontally; VLOOKUP searche...,Find & Replace data in Excel through the Home ...,COUNT counts numbers; COUNTA counts non-empty ...,Conditional formatting visually highlights dat...,...,"To prevent duplicate records, use the DISTINCT...",Renaming a column changes its permanent name i...,Power BI is a Microsoft business analytics too...,"Power Query is for data transformation, while ...",Power BI Desktop is a free application for cre...,Data modeling in Power BI involves structuring...,Power Query is a data connection and transform...,DAX is a formula language in Power BI for cust...,Filters in Power BI narrow down data displayed...,GetData in Power BI retrieves data from extern...
Tool_Question,excel_answer_1,excel_answer_2,excel_answer_3,excel_answer_4,excel_answer_5,excel_answer_6,excel_answer_7,excel_answer_8,excel_answer_9,excel_answer_10,...,sql_answer_10,sql_answer_11,power_bi_answer_1,power_bi_answer_2,power_bi_answer_3,power_bi_answer_4,power_bi_answer_5,power_bi_answer_6,power_bi_answer_7,power_bi_answer_8

In [57]:
# swapping the columns and rows
df_2.columns = df_2.iloc[1]

In [58]:
df_2

Tool_Question,excel_answer_1,excel_answer_2,excel_answer_3,excel_answer_4,excel_answer_5,excel_answer_6,excel_answer_7,excel_answer_8,excel_answer_9,excel_answer_10,...,sql_answer_10,sql_answer_11,power_bi_answer_1,power_bi_answer_2,power_bi_answer_3,power_bi_answer_4,power_bi_answer_5,power_bi_answer_6,power_bi_answer_7,power_bi_answer_8
Answer,"Excel is used for data management, analysis, a...",A workbook contains multiple sheets; a workshe...,VLOOKUP finds and retrieves data based on a ma...,CONCATENATE combines text or cell values into ...,Remove duplicates in Excel by selecting data a...,PivotTable summarizes and analyzes data for in...,HLOOKUP searches horizontally; VLOOKUP searche...,Find & Replace data in Excel through the Home ...,COUNT counts numbers; COUNTA counts non-empty ...,Conditional formatting visually highlights dat...,...,"To prevent duplicate records, use the DISTINCT...",Renaming a column changes its permanent name i...,Power BI is a Microsoft business analytics too...,"Power Query is for data transformation, while ...",Power BI Desktop is a free application for cre...,Data modeling in Power BI involves structuring...,Power Query is a data connection and transform...,DAX is a formula language in Power BI for cust...,Filters in Power BI narrow down data displayed...,GetData in Power BI retrieves data from extern...
Tool_Question,excel_answer_1,excel_answer_2,excel_answer_3,excel_answer_4,excel_answer_5,excel_answer_6,excel_answer_7,excel_answer_8,excel_answer_9,excel_answer_10,...,sql_answer_10,sql_answer_11,power_bi_answer_1,power_bi_answer_2,power_bi_answer_3,power_bi_answer_4,power_bi_answer_5,power_bi_answer_6,power_bi_answer_7,power_bi_answer_8

In [59]:
# dropping the second row
df_3 = df_2.drop('Tool_Question')

In [60]:
df_3

Tool_Question,excel_answer_1,excel_answer_2,excel_answer_3,excel_answer_4,excel_answer_5,excel_answer_6,excel_answer_7,excel_answer_8,excel_answer_9,excel_answer_10,...,sql_answer_10,sql_answer_11,power_bi_answer_1,power_bi_answer_2,power_bi_answer_3,power_bi_answer_4,power_bi_answer_5,power_bi_answer_6,power_bi_answer_7,power_bi_answer_8
Answer,"Excel is used for data management, analysis, a...",A workbook contains multiple sheets; a workshe...,VLOOKUP finds and retrieves data based on a ma...,CONCATENATE combines text or cell values into ...,Remove duplicates in Excel by selecting data a...,PivotTable summarizes and analyzes data for in...,HLOOKUP searches horizontally; VLOOKUP searche...,Find & Replace data in Excel through the Home ...,COUNT counts numbers; COUNTA counts non-empty ...,Conditional formatting visually highlights dat...,...,"To prevent duplicate records, use the DISTINCT...",Renaming a column changes its permanent name i...,Power BI is a Microsoft business analytics too...,"Power Query is for data transformation, while ...",Power BI Desktop is a free application for cre...,Data modeling in Power BI involves structuring...,Power Query is a data connection and transform...,DAX is a formula language in Power BI for cust...,Filters in Power BI narrow down data displayed...,GetData in Power BI retrieves data from extern...

In [61]:
# saving this dataframe to a new csv file
df_3.to_csv('data_000.csv')

In [62]:
from rouge import Rouge

# Example generated and reference texts
generated_text = "This is a sample summary."
reference_text = "This is a reference summary."

# Initialize Rouge
rouge = Rouge()

# Compute Rouge scores
scores = rouge.get_scores(generated_text, reference_text)

# Print Rouge scores
print(scores[0]['rouge-1']['r'])

0.8

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Example generated and reference texts
generated_text = "This is a sample summary."
reference_text = "This is a sample summary."

# Convert text to TF-IDF vectors
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform([generated_text, reference_text])

# Compute cosine similarity
cosine_sim = cosine_similarity(tfidf_matrix[0], tfidf_matrix[1])

print("Cosine Similarity:", cosine_sim[0][0])

Cosine Similarity: 1.0

In [64]:
from rouge import Rouge

# Example lists of generated sentences and reference sentences
generated_sentences = ["This is a sample summary 1.", "This is a sample summary 2."]
reference_sentences = ["This is a sample summary 1.", "This is a reference summary 2."]

# Initialize Rouge
rouge = Rouge()

# Initialize variables to store aggregated Rouge scores
total_rouge_1_r = 0
total_rouge_2_r = 0
total_rouge_l_r = 0

# Compute Rouge scores for each pair of sentences
for gen_sentence, ref_sentence in zip(generated_sentences, reference_sentences):
    scores = rouge.get_scores(gen_sentence, ref_sentence)[0]
    total_rouge_1_r += scores['rouge-1']['r']


# Calculate average Rouge scores
num_sentences = len(generated_sentences)
avg_rouge_1_r = total_rouge_1_r / num_sentences

# Normalize Rouge scores to a scale of 0 to 100%
normalized_rouge_1_r = avg_rouge_1_r * 100


print("Normalized Rouge-1 Recall:", normalized_rouge_1_r)


# putting this in a function
def calculate_rouge_scores(generated_sentences, reference_sentences):
    # Initialize Rouge
    rouge = Rouge()

    # Initialize variables to store aggregated Rouge scores
    total_rouge_1_r = 0
    total_rouge_2_r = 0
    total_rouge_l_r = 0

    # Compute Rouge scores for each pair of sentences
    for gen_sentence, ref_sentence in zip(generated_sentences, reference_sentences):
        scores = rouge.get_scores(gen_sentence, ref_sentence)[0]
        total_rouge_1_r += scores['rouge-1']['r']

    # Calculate average Rouge scores
    num_sentences = len(generated_sentences)
    avg_rouge_1_r = total_rouge_1_r / num_sentences

    # Normalize Rouge scores to a scale of 0 to 100%
    normalized_rouge_1_r = avg_rouge_1_r * 100

    return normalized_rouge_1_r

Normalized Rouge-1 Recall: 91.66666666666667

In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Example lists of generated sentences and reference sentences
generated_sentences = [
    "This is a sample summary 1.",
    "This is a sample summary 2."
]

reference_sentences = [
    "This is a reference summary 1.",
    "This is a reference summary 2."
]

# Initialize the TF-IDF vectorizer
vectorizer = TfidfVectorizer()

# Fit and transform the sentences to TF-IDF vectors
tfidf_matrix_generated = vectorizer.fit_transform(generated_sentences)
tfidf_matrix_reference = vectorizer.transform(reference_sentences)

# Compute cosine similarity between the generated and reference sentences
cosine_similarities = cosine_similarity(tfidf_matrix_generated, tfidf_matrix_reference)

print("Cosine Similarity Matrix:")
print(cosine_similarities)

# placing in a function
def calculate_cosine_similarity(generated_sentences):
    # loading the reference dataaset
    df  = pd.read_csv('data_000.csv')
    reference_sentences = df.iloc[0].tolist()[1:]
    # Initialize the TF-IDF vectorizer
    vectorizer = TfidfVectorizer()

    # Fit and transform the sentences to TF-IDF vectors
    tfidf_matrix_reference = vectorizer.fit_transform(reference_sentences)
    tfidf_matrix_generated = vectorizer.transform(generated_sentences)
    

    # Compute cosine similarity between the generated and reference sentences
    cosine_similarities = cosine_similarity(tfidf_matrix_reference, tfidf_matrix_generated)

    return cosine_similarities[0][0]

Cosine Similarity Matrix:
[[0.8660254 0.8660254]
 [0.8660254 0.8660254]]

In [66]:
df  = pd.read_csv('data_000.csv')
reference_sentences = df.iloc[0].tolist()[1:]
reference_sentences

['Excel is used for data management, analysis, and visualization.',
 'A workbook contains multiple sheets; a worksheet is a single sheet.',
 'VLOOKUP finds and retrieves data based on a matching value.',
 'CONCATENATE combines text or cell values into one.',
 "Remove duplicates in Excel by selecting data and using 'Remove Duplicates.'",
 'PivotTable summarizes and analyzes data for insights.',
 'HLOOKUP searches horizontally; VLOOKUP searches vertically.',
 'Find & Replace data in Excel through the Home tab.',
 'COUNT counts numbers; COUNTA counts non-empty cells; COUNTIF counts based on criteria; COUNTIFS counts with multiple criteria.',
 'Conditional formatting visually highlights data based on conditions.',
 'Comparative operators compare values; IF statements make decisions based on conditions.',
 'Use the ROUND function to round values to 2 decimal places.',
 'Relative cell references adjust when copied; absolute references stay fixed.',
 'Line charts show trends over time; scatterplots display correlations between variables.',
 'TRIM removes extra spaces from text strings.',
 'Link data between worksheets using cell references or named ranges.',
 'Filtering displays specific rows; sorting arranges data by values.',
 'SQL is Structured Query Language, used for managing data in relational databases.',
 'An SQL statement is a command like SELECT, INSERT, UPDATE, or DELETE used to perform tasks in a database.',
 'A database is a structured collection of data. DBMS is software to manage databases, with types like relational (RDBMS), hierarchical, network, and object-oriented. Examples of RDBMS include MySQL, PostgreSQL, Oracle.',
 'A join combines rows from different tables based on related columns. Types include INNER JOIN, LEFT JOIN, RIGHT JOIN, and FULL JOIN.',
 'Primary key uniquely identifies each record in a table. Unique key ensures uniqueness but allows null values. Foreign key establishes relationships between tables.',
 'A schema represents the logical structure of data in a database, including tables, relationships, and constraints.',
 'CASE() function performs conditional logic in SQL, returning a result based on specified conditions.',
 'SELECT retrieves data, FROM specifies the table, JOIN combines tables, ON specifies join condition, WHERE filters rows, GROUP BY groups rows, HAVING filters grouped data, ORDER BY sorts results, LIMIT limits rows returned.',
 'BOOLEAN data field can have values TRUE, FALSE, and sometimes NULL.',
 'To prevent duplicate records, use the DISTINCT keyword in your SELECT statement.',
 'Renaming a column changes its permanent name in the table, while giving an alias provides a temporary name in a specific query.',
 'Power BI is a Microsoft business analytics tool for data visualization, analysis, and sharing insights.',
 'Power Query is for data transformation, while Power Pivot is for data modeling and relationships in Power BI.',
 'Power BI Desktop is a free application for creating Power BI reports and dashboards on desktop computers.',
 'Data modeling in Power BI involves structuring data, creating relationships, and optimizing for analysis.',
 'Power Query is a data connection and transformation technology used in Microsoft Excel and Power BI. It allows users to easily connect to various data sources, transform data using a visual interface, and load it into their analysis tools.',
 'DAX is a formula language in Power BI for custom calculations and analysis on data.',
 'Filters in Power BI narrow down data displayed in visuals based on specific criteria.',
 'GetData in Power BI retrieves data from external sources for import into Power BI models.']

In [67]:
# getting the first row in the data
copy_1 = df_3.iloc[0].tolist()
copy_2 = df_3.iloc[0].tolist()

In [68]:
copy_1

['Excel is used for data management, analysis, and visualization.',
 'A workbook contains multiple sheets; a worksheet is a single sheet.',
 'VLOOKUP finds and retrieves data based on a matching value.',
 'CONCATENATE combines text or cell values into one.',
 "Remove duplicates in Excel by selecting data and using 'Remove Duplicates.'",
 'PivotTable summarizes and analyzes data for insights.',
 'HLOOKUP searches horizontally; VLOOKUP searches vertically.',
 'Find & Replace data in Excel through the Home tab.',
 'COUNT counts numbers; COUNTA counts non-empty cells; COUNTIF counts based on criteria; COUNTIFS counts with multiple criteria.',
 'Conditional formatting visually highlights data based on conditions.',
 'Comparative operators compare values; IF statements make decisions based on conditions.',
 'Use the ROUND function to round values to 2 decimal places.',
 'Relative cell references adjust when copied; absolute references stay fixed.',
 'Line charts show trends over time; scatterplots display correlations between variables.',
 'TRIM removes extra spaces from text strings.',
 'Link data between worksheets using cell references or named ranges.',
 'Filtering displays specific rows; sorting arranges data by values.',
 'SQL is Structured Query Language, used for managing data in relational databases.',
 'An SQL statement is a command like SELECT, INSERT, UPDATE, or DELETE used to perform tasks in a database.',
 'A database is a structured collection of data. DBMS is software to manage databases, with types like relational (RDBMS), hierarchical, network, and object-oriented. Examples of RDBMS include MySQL, PostgreSQL, Oracle.',
 'A join combines rows from different tables based on related columns. Types include INNER JOIN, LEFT JOIN, RIGHT JOIN, and FULL JOIN.',
 'Primary key uniquely identifies each record in a table. Unique key ensures uniqueness but allows null values. Foreign key establishes relationships between tables.',
 'A schema represents the logical structure of data in a database, including tables, relationships, and constraints.',
 'CASE() function performs conditional logic in SQL, returning a result based on specified conditions.',
 'SELECT retrieves data, FROM specifies the table, JOIN combines tables, ON specifies join condition, WHERE filters rows, GROUP BY groups rows, HAVING filters grouped data, ORDER BY sorts results, LIMIT limits rows returned.',
 'BOOLEAN data field can have values TRUE, FALSE, and sometimes NULL.',
 'To prevent duplicate records, use the DISTINCT keyword in your SELECT statement.',
 'Renaming a column changes its permanent name in the table, while giving an alias provides a temporary name in a specific query.',
 'Power BI is a Microsoft business analytics tool for data visualization, analysis, and sharing insights.',
 'Power Query is for data transformation, while Power Pivot is for data modeling and relationships in Power BI.',
 'Power BI Desktop is a free application for creating Power BI reports and dashboards on desktop computers.',
 'Data modeling in Power BI involves structuring data, creating relationships, and optimizing for analysis.',
 'Power Query is a data connection and transformation technology used in Microsoft Excel and Power BI. It allows users to easily connect to various data sources, transform data using a visual interface, and load it into their analysis tools.',
 'DAX is a formula language in Power BI for custom calculations and analysis on data.',
 'Filters in Power BI narrow down data displayed in visuals based on specific criteria.',
 'GetData in Power BI retrieves data from external sources for import into Power BI models.']

In [69]:
copy_3 = [
    "Excel is primarily used for data management, analysis, and visualization. It allows users to create spreadsheets, perform calculations, organize data, and generate charts and graphs.",
    "A workbook in Excel is like a file that can contain multiple worksheets. Each worksheet is a single spreadsheet within the workbook where data can be entered and manipulated separately.",
    "VLOOKUP is a function in Excel used to search for a value in the first column of a range, and then return a value in the same row from a specified column.",
    "The CONCATENATE function in Excel is used to combine multiple strings or cell values into one string.",
    "Duplicates in Excel can be removed using the 'Remove Duplicates' feature found in the 'Data' tab. This feature allows users to select the columns from which duplicates should be removed.",
    "A PivotTable in Excel is a powerful tool used to summarize and analyze large datasets. It allows users to reorganize and summarize data, perform calculations, and create interactive reports.",
    "HLOOKUP and VLOOKUP are both lookup functions in Excel, but they differ in their orientation. HLOOKUP searches for a value in the first row of a table and returns a value in the same column from a specified row, while VLOOKUP searches for a value in the first column of a table and returns a value in the same row from a specified column.",
    "To find and replace data in Excel, you can use the 'Find and Replace' feature located in the 'Editing' group on the 'Home' tab. This feature allows you to search for specific text or numbers and replace them with new values.",
    "COUNT, COUNTA, COUNTIF, and COUNTIFS are all counting functions in Excel, but they differ in their usage. COUNT counts the number of cells that contain numbers, COUNTA counts the number of cells that are not empty, COUNTIF counts the number of cells that meet a specific criterion, and COUNTIFS counts the number of cells that meet multiple criteria.",
    "Conditional formatting in Excel allows users to format cells based on certain conditions or criteria. This can include highlighting cells that meet certain criteria, applying color scales, or adding data bars to visually represent data.",
    "Comparative operators, logical tests, and IF statements are used in Excel to perform conditional logic. They allow users to compare values, perform logical tests, and execute different actions based on the results.",
    "To round values in a whole column to 2 decimal places in Excel, you can use the 'ROUND' function. For example, if your values are in column A, you can use the formula =ROUND(A:A, 2) to round them to 2 decimal places.",
    "Relative cell references in Excel change when copied or filled, whereas absolute cell references remain constant. Relative references are identified by letters and numbers (e.g., A1), while absolute references are identified by dollar signs (e.g., $A$1).",
    "A line chart in Excel is used to display data points connected by straight lines, while a scatterplot is used to display the relationship between two variables with points. Line charts are typically used to show trends over time, while scatterplots are used to show correlations between variables.",
    "The TRIM function in Excel is used to remove extra spaces from text, both at the beginning and end of a string, as well as extra spaces between words.",
    "Data can be linked between different worksheets in Excel by using cell references. By referencing cells in other worksheets using formulas or functions, changes made in one worksheet can automatically update in another.",
    "In Excel, 'filter' refers to the process of displaying only specific data based on certain criteria, while 'sort' refers to arranging data in ascending or descending order based on one or more columns.",
    "SQL (Structured Query Language) is a programming language used for managing and manipulating relational databases. It allows users to perform tasks such as querying data, inserting and updating records, and defining and modifying database structures.",
    "An SQL statement is a command written in SQL that instructs the database management system (DBMS) to perform a specific action. Examples include SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, and DROP statements.",
    "A database is a collection of related data organized in a structured format. DBMS (Database Management System) is software that enables users to interact with databases. RDBMS (Relational Database Management System) is a type of DBMS that stores data in tables and enforces relationships between them. Examples of RDBMS include MySQL, PostgreSQL, Oracle, and SQL Server.",
    "A join in SQL is used to combine rows from two or more tables based on a related column between them. Types of joins include INNER JOIN, LEFT JOIN (or LEFT OUTER JOIN), RIGHT JOIN (or RIGHT OUTER JOIN), and FULL JOIN (or FULL OUTER JOIN), each serving different purposes.",
    "A primary key in SQL is a column or a set of columns that uniquely identifies each record in a table. A unique key is similar to a primary key but allows NULL values. A foreign key is a column or a set of columns that establishes a relationship between two tables.",
    "A schema in SQL is a collection of database objects (such as tables, views, and procedures) associated with a particular database user or group. It defines the structure of the database and the relationships between its objects.",
    "The CASE() function in SQL is a conditional expression that returns a value based on one or more conditions. It is similar to the 'if...else' statement in other programming languages.",
    "SELECT retrieves data from one or more tables, FROM specifies the table(s) from which to retrieve data, JOIN combines rows from two or more tables based on a related column, ON specifies the join condition, WHERE filters rows based on a condition, GROUP BY groups rows that have the same values into summary rows, HAVING filters groups based on a condition, ORDER BY sorts the result set in ascending or descending order, and LIMIT restricts the number of rows returned by a query.",
    "The possible values of a BOOLEAN data field in SQL are TRUE, FALSE, and NULL.",
    "Duplicate records can be prevented in SQL queries by using the DISTINCT keyword, which removes duplicate rows from the result set.",
    "Renaming a column in SQL changes its name in the table definition, while giving an alias to it changes its display name in query results without altering the table definition.",
    "Power BI is a business analytics tool developed by Microsoft that allows users to visualize and analyze data from various sources. It includes features for data preparation, data modeling, visualization, and collaboration.",
    "Power Query is a data connectivity and transformation tool in Power BI used to import, transform, and clean data from various sources before loading it into the data model. Power Pivot is an in-memory data modeling engine used to create data models and perform complex calculations.",
    "Power BI Desktop is a free desktop application used to create and publish Power BI reports and dashboards. It provides a user-friendly interface for importing data, building visualizations, and designing interactive reports.",
    "Data modeling in Power BI involves defining relationships between tables, creating calculated columns and measures, and building hierarchies to enable interactive analysis and visualization of data.",
    "Power Query is a data connectivity and transformation tool in Power BI used to import, transform, and clean data from various sources before loading it into the data model.",
    "DAX (Data Analysis Expressions) is a formula language used in Power BI to perform calculations, define calculated columns and measures, and create custom calculations for data analysis.",
    "Filters in Power BI are used to narrow down the data displayed in reports and visualizations based on specific criteria. They can be applied at the report, page, or visual level.",
    "GetData is a function in Power BI used to import data from various sources, such as Excel files, databases, or online services, into Power BI Desktop for analysis and visualization."
]

In [70]:
# testing 
calculate_cosine_similarity(copy_3)

0.6678707272144107

In [71]:
len(copy_3)

36

In [72]:
calculate_rouge_scores(copy_1, copy_3)

31.32588757995508